---
name: Bio-GenBankParser
version: 0.01
author:
  - 'Ken Youens-Clark <kclark@cshl.edu>'
abstract: Parse::RecDescent parser for a GenBank record
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Parse::RecDescent: 1.94
build_requires:
  Test::More: 0
provides:
  Bio::GenBankParser:
    file: lib/Bio/GenBankParser.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
