---
abstract: 'Parse::RecDescent parser for a GenBank record'
author:
  - 'Ken Youens-Clark <kclark@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-GenBankParser
provides:
  Bio::GenBankParser:
    file: lib/Bio/GenBankParser.pm
    version: 0.05
recommends:
  YAML: 0
requires:
  Parse::RecDescent: 1.965001
  Readonly: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
